# Generated by Django 3.0 on 2019-12-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='by_who',
            field=models.CharField(default=None, max_length=150, verbose_name='Created by'),
        ),
    ]
