# Generated by Django 3.0 on 2019-12-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20191205_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='by_who',
            field=models.CharField(max_length=150, verbose_name='Created by'),
        ),
    ]
