# Generated by Django 3.0.2 on 2020-02-03 12:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0013_auto_20200203_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='viewable_by',
        ),
        migrations.AddField(
            model_name='task',
            name='viewable_by',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
