# Generated by Django 3.0.2 on 2020-02-08 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0014_auto_20200203_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='viewable_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
