# Generated by Django 3.0.2 on 2020-02-08 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0015_auto_20200208_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='editable_by',
            field=models.ManyToManyField(related_name='editable_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='viewable_by',
            field=models.ManyToManyField(related_name='viewable_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
