# Generated by Django 3.0.2 on 2020-02-11 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20200208_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_sender', models.CharField(max_length=250, verbose_name='Comment author')),
                ('comment_text', models.CharField(max_length=250, verbose_name='Comment text')),
                ('comment_date', models.DateTimeField()),
                ('comment_related_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Task')),
            ],
        ),
    ]
